### ISSUE TITLE
Awesome Mod Thank you!!!!!!

### ISSUE THREAD

**Issue by treboR-0** [derbl4ck/jc3mp-minimap#1]
No Opacity. Wrong side. Wrong shape. Wrong Size. But Awesome Mod Thank you!!!!!!
 https://www.gta5-mods.com/scripts/big-map was resizable Perfection. Except it needed one more size that covers the entire screen with an opaque full map
Will it show blips?

**Comment by derbl4ck** [comment]
You can adjust the position & size in the next version. Thank you for your feedback.

**Comment by sebi2306** [comment]
How do you do that?
